import Toast_Provider from './components/Toast_Provider'
import './globals.css'

import { Noto_Sans } from 'next/font/google'

const inter = Noto_Sans({ subsets: ['latin'] , weight : ['500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
} : {
    children : React.ReactNode
})
   {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Toast_Provider/>
        {children}
        </body>
    </html>
  )
}
